=== clemy/RayTracer/examples2/scene.dtd
<!ELEMENT scene (background_color, animation?, still?, motionblur?, caustic?, camera, lights, surfaces)>
<!ELEMENT background_color EMPTY>
<!ELEMENT animation EMPTY>
<!ELEMENT still EMPTY>
<!ELEMENT motionblur EMPTY>
<!ELEMENT caustic EMPTY>

<!ELEMENT camera (position, lookat, up, horizontal_fov, resolution, max_bounces, supersampling?, dof?)>
<!ELEMENT position EMPTY>
<!ELEMENT lookat EMPTY>
<!ELEMENT up EMPTY>
<!ELEMENT horizontal_fov EMPTY>
<!ELEMENT resolution EMPTY>
<!ELEMENT max_bounces EMPTY>
<!ELEMENT supersampling EMPTY>
<!ELEMENT dof EMPTY>

<!ELEMENT lights ((ambient_light | point_light | parallel_light | spot_light)*)>
<!ELEMENT ambient_light (color)>
<!ELEMENT point_light (color, position)>
<!ELEMENT parallel_light (color, direction)>
<!ELEMENT spot_light (color, position, direction, falloff)>
<!ELEMENT color EMPTY>
<!ELEMENT direction EMPTY>
<!ELEMENT falloff EMPTY>

<!ELEMENT surfaces ((sphere | mesh | julia)*)>
<!ELEMENT sphere (position, (material_solid | material_textured), transform?)>
<!ELEMENT mesh ((material_solid | material_textured), transform?)>
<!ELEMENT julia (position, material_solid, transform?)>

<!ELEMENT material_solid (color, phong, reflectance, transmittance, refraction)>
<!ELEMENT material_textured (texture, phong, reflectance, transmittance, refraction)>
<!ELEMENT phong EMPTY>
<!ELEMENT reflectance EMPTY>
<!ELEMENT transmittance EMPTY>
<!ELEMENT refraction EMPTY>
<!ELEMENT texture EMPTY>

<!ELEMENT transform ((translate | scale | rotateX | rotateY | rotateZ)*)>
<!ELEMENT translate EMPTY>
<!ELEMENT scale EMPTY>
<!ELEMENT rotateX EMPTY>
<!ELEMENT rotateY EMPTY>
<!ELEMENT rotateZ EMPTY>



<!ATTLIST scene
	output_file CDATA #REQUIRED
  time CDATA #IMPLIED
	threads NMTOKEN #IMPLIED>

<!ATTLIST background_color
	r CDATA #REQUIRED
	g CDATA #REQUIRED
	b CDATA #REQUIRED
  a CDATA #IMPLIED>

<!ATTLIST animation
	length NMTOKEN #REQUIRED
	fps CDATA #REQUIRED>

<!ATTLIST still
	time CDATA #REQUIRED>

<!ATTLIST motionblur
	subframes CDATA #REQUIRED>

<!ATTLIST caustic
	steps CDATA #REQUIRED
  texture_size NMTOKEN #REQUIRED
  factor CDATA #REQUIRED>

<!ATTLIST position
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>

<!ATTLIST lookat
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>	

<!ATTLIST up
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>

<!ATTLIST horizontal_fov
	angle CDATA #REQUIRED>

<!ATTLIST resolution
	horizontal NMTOKEN #REQUIRED
	vertical NMTOKEN #REQUIRED>

<!ATTLIST max_bounces
	n CDATA #REQUIRED>

<!ATTLIST supersampling
	subpixels_peraxis CDATA #REQUIRED>

<!ATTLIST dof
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
  lenssize CDATA #REQUIRED>

<!ATTLIST color
	r CDATA #REQUIRED
	g CDATA #REQUIRED
	b CDATA #REQUIRED
	a CDATA #IMPLIED>

<!ATTLIST direction
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>

<!ATTLIST falloff
	alpha1 CDATA #REQUIRED
	alpha2 CDATA #REQUIRED>

<!ATTLIST sphere
	radius CDATA #REQUIRED>

<!ATTLIST mesh
	name CDATA #REQUIRED>

<!ATTLIST julia
	scale CDATA #REQUIRED
	cr CDATA #REQUIRED
	ca CDATA #REQUIRED
	cb CDATA #REQUIRED
	cc CDATA #REQUIRED
	cutplane CDATA #REQUIRED>

<!ATTLIST phong
	ka CDATA #REQUIRED
	kd CDATA #REQUIRED
	ks CDATA #REQUIRED
	exponent CDATA #REQUIRED>

<!ATTLIST reflectance
	r CDATA #REQUIRED>

<!ATTLIST transmittance
	t CDATA #REQUIRED>

<!ATTLIST refraction
	iof CDATA #REQUIRED
  ec CDATA #IMPLIED
  disp CDATA #IMPLIED>

<!ATTLIST texture
	name CDATA #REQUIRED>

<!ATTLIST translate
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>

<!ATTLIST scale
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>

<!ATTLIST rotateX
	theta CDATA #REQUIRED>

<!ATTLIST rotateY
	theta CDATA #REQUIRED>

<!ATTLIST rotateZ
	theta CDATA #REQUIRED>

=== clemy/RayTracer/wasm/examples/7_dof.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE scene SYSTEM "scene.dtd">

<scene output_file="7_dof.png">
  <background_color r="0.0" g="0.0" b="0.0"/>
  <camera>
    <position x="2.0" y="2.0" z="1.0"/>
    <lookat x="0.0" y="1.5" z="-2.5"/>
    <up x="0.0" y="1.0" z="0.0"/>
    <horizontal_fov angle="45"/>
    <resolution horizontal="512" vertical="512"/>
    <max_bounces n="8"/>
    <supersampling subpixels_peraxis="7"/>
    <dof x="0.71" y="0.5" z="-2.29" lenssize="0.25"/>
  </camera>
  <lights>
    <ambient_light>
      <color r="1.0" g="1.0" b="1.0"/>
    </ambient_light>
    <point_light>
      <color r="0.5" g="0.5" b="0.5"/>
      <position x="2.0" y="3.0" z="-2.5"/>
    </point_light>
    <point_light>
      <color r="0.5" g="0.5" b="0.5"/>
      <position x="-2.0" y="3.0" z="-2.5"/>
    </point_light>
    <point_light>
      <color r="0.5" g="0.5" b="0.5"/>
      <position x="0.0" y="0.0" z="-0.5"/>
    </point_light>
  </lights>
  <surfaces>
    <sphere radius="1.0">
      <position x="-2.1" y="1.5" z="-6.0"/>
      <material_textured>
        <texture name="mramor6x6.png"/>
        <phong ka="0.3" kd="0.9" ks="1.0" exponent="200"/>
        <reflectance r="0.0"/>
        <transmittance t="0.0"/>
        <refraction iof="0.0"/>
      </material_textured>
    </sphere>
    <sphere radius="1.0">
      <position x="0.0" y="0.5" z="-3.0"/>
      <material_textured>
        <texture name="mramor6x6.png"/>
        <phong ka="0.5" kd="0.9" ks="1.0" exponent="200"/>
        <reflectance r="0.0"/>
        <transmittance t="0.0"/>
        <refraction iof="0.0"/>
      </material_textured>
    </sphere>
    <sphere radius="1.0">
      <position x="2.1" y="-1.5" z="-7.0"/>
      <material_textured>
        <texture name="mramor6x6.png"/>
        <phong ka="0.3" kd="0.7" ks="1.0" exponent="200"/>
        <reflectance r="0.0"/>
        <transmittance t="0.0"/>
        <refraction iof="0.0"/>
      </material_textured>
    </sphere>
    <sphere radius="1.0">
      <position x="-2.1" y="-1.5" z="-3.0"/>
      <material_textured>
        <texture name="mramor6x6.png"/>
        <phong ka="0.3" kd="0.9" ks="1.0" exponent="200"/>
        <reflectance r="0.0"/>
        <transmittance t="0.0"/>
        <refraction iof="0.0"/>
      </material_textured>
    </sphere>
    <sphere radius="1.0">
      <position x="1.4" y="2.8" z="-5.7"/>
      <material_textured>
        <texture name="mramor6x6.png"/>
        <phong ka="0.5" kd="0.6" ks="1.0" exponent="200"/>
        <reflectance r="0.0"/>
        <transmittance t="0.0"/>
        <refraction iof="0.0"/>
      </material_textured>
    </sphere>
    <sphere radius="1.0">
      <position x="-2.0" y="2.5" z="-3.0"/>
      <material_textured>
        <texture name="mramor6x6.png"/>
        <phong ka="0.3" kd="0.9" ks="1.0" exponent="200"/>
        <reflectance r="0.0"/>
        <transmittance t="0.0"/>
        <refraction iof="0.0"/>
      </material_textured>
    </sphere>
    <mesh name="open_room.obj">
      <material_textured>
        <texture name="rainbow.png"/>
        <phong ka="0.3" kd="0.9" ks="1.0" exponent="20"/>
        <reflectance r="0.0"/>
        <transmittance t="0.0"/>
        <refraction iof="0.0"/>
      </material_textured>
    </mesh>
  </surfaces>
</scene>

=== clemy/RayTracer/wasm/examples/9_caustic.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE scene SYSTEM "scene.dtd">

<scene output_file="9_caustic.png">
    <background_color r="0.0" g="0.0" b="0.0"/>
    <caustic steps="2400" texture_size="300" factor="0.0225"/>
    <camera>
        <position x="2.9" y="1.9" z="-3.3"/>
        <lookat x="0.0" y="0.0" z="-6.5"/>
        <up x="0.0" y="1.0" z="0.0"/>
        <horizontal_fov angle="38"/>
        <resolution horizontal="512" vertical="512"/>
        <max_bounces n="8"/>
        <supersampling subpixels_peraxis="1"/>
    </camera>
    <lights>
        <ambient_light>
            <color r="1.0" g="1.0" b="1.0"/>
        </ambient_light>
        <point_light>
            <color r="0.7" g="0.7" b="0.7"/>
            <position x="2.0" y="3.0" z="-2.5"/>
        </point_light>
        <point_light>
            <color r="0.7" g="0.7" b="0.7"/>
            <position x="-2.0" y="3.0" z="-2.5"/>
        </point_light>
    </lights>
    <surfaces>
        <mesh name="open_room.obj">
            <material_solid>
                <color r="0.6" g="0.6" b="0.6"/>
                <phong ka="0.3" kd="0.9" ks="0.8" exponent="200"/>
                <reflectance r="0.0"/>
                <transmittance t="0.0"/>
                <refraction iof="0.0"/>
            </material_solid>
        </mesh>
        <mesh name="box2.obj">
            <material_solid>
                <color r="0.17" g="0.18" b="0.50"/>
                <phong ka="0.0" kd="0.0" ks="0.0" exponent="200"/>
                <reflectance r="0.8"/>
                <transmittance t="0.8"/>
                <refraction iof="1.5168" ec="9.7525e-9" disp="-0.15"/>
            </material_solid>
        </mesh>
    </surfaces>
</scene>

=== clemy/RayTracer/examples2/dtd-test.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE scene SYSTEM "scene.dtd">

<scene output_file="myImage.png" threads="1">
	<background_color r="255" g="0" b="0" a="0"/>
  <animation length="1" fps="25"/>
	<camera>
		<position x="1.0" y="-2.0E-10" z="-3"/>
		<lookat x="1" y="2" z="3"/>
		<up x="1" y="2" z="3"/>
		<horizontal_fov angle="90"/>
		<resolution horizontal="1920" vertical="1080"/>
		<max_bounces n="100"/>
	</camera>
	<lights>
		<ambient_light>
			<color r="1" g="2" b="3"/>
		</ambient_light>
		<point_light>
			<color r="1" g="2" b="3"/>
			<position x="1" y="2" z="3"/>
		</point_light>
		<parallel_light>
			<color r="1" g="2" b="3"/>
			<direction x="1" y="2" z="3"/>
		</parallel_light>
		<spot_light>
			<color r="1" g="2" b="3"/>
			<position x="1" y="2" z="3"/>
			<direction x="1" y="2" z="3"/>
			<falloff alpha1="1" alpha2="3"/>
		</spot_light>
	</lights>
	<surfaces>
		<sphere radius="123">
			<position x="1" y="2" z="3"/>
			<material_solid>
				<color r="1" g="2" b="3"/>
				<phong ka="1" kd="1" ks="1" exponent="1"/>
				<reflectance r="1"/>
				<transmittance t="1"/>
				<refraction iof="1"/>
			</material_solid>
			<transform>
				<translate x="1" y="1" z="1"/>
				<scale x="1" y="1" z="1"/>
				<rotateX theta="1"/>
				<rotateY theta="1"/>
				<rotateZ theta="1"/>
			</transform>
		</sphere>
		<mesh name="duck.dae">
			<material_textured>
				<texture name=""/>
				<phong ka="1" kd="1" ks="1" exponent="1"/>
				<reflectance r="1"/>
				<transmittance t="1"/>
				<refraction iof="1"/>
			</material_textured>
			<transform>
				<translate x="1" y="1" z="1"/>
				<scale x="1" y="1" z="1"/>
				<rotateX theta="1"/>
				<rotateY theta="1"/>
				<rotateZ theta="1"/>
				<translate x="1" y="1" z="1"/>
				<scale x="1" y="1" z="1"/>
			</transform>
		</mesh>
    <julia scale="1" cr="1" ca="2" cb="3" cc="4" cutplane="0">
      <position x="1" y="2" z="3"/>
      <material_solid>
        <color r="1" g="2" b="3"/>
        <phong ka="1" kd="1" ks="1" exponent="1"/>
        <reflectance r="1"/>
        <transmittance t="1"/>
        <refraction iof="1"/>
      </material_solid>
      <transform>
        <translate x="1" y="1" z="1"/>
        <scale x="1" y="1" z="1"/>
        <rotateX theta="1"/>
        <rotateY theta="1"/>
        <rotateZ theta="1"/>
      </transform>
    </julia>
  </surfaces>
</scene>

=== clemy/RayTracer/wasm/examples/101_julia_shiny.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE scene SYSTEM "scene.dtd">

<scene output_file="101_julia_shiny.png">
    <background_color r="0.0" g="0.0" b="0.1" a="1"/>
    <camera>
        <position x="0.0" y="0.0" z="1.0"/>
        <lookat x="0.0" y="0.0" z="-2.5"/>
        <up x="0.0" y="1.0" z="0.0"/>
        <horizontal_fov angle="22.5"/>
        <resolution horizontal="640" vertical="400"/>
        <supersampling subpixels_peraxis="2"/>
        <max_bounces n="5"/>
    </camera>
    <lights>
        <ambient_light>
            <color r="0.1" g="0.1" b="0.1"/>
        </ambient_light>
        <point_light>
            <color r="0.25" g="0.55" b="0.05"/>
            <position x="-30" y="25" z="0"/>
        </point_light>
        <point_light>
            <color r="0.45" g="0.45" b="0.45"/>
            <position x="2.0" y="5.0" z="0"/>
        </point_light>
        <point_light>
            <color r="0.0" g="0.0" b="0.45"/>
            <position x="20" y="0" z="-20"/>
        </point_light>
    </lights>
    <surfaces>
        <julia scale="13" cr="-0.291" ca="-0.399" cb="0.339" cc="0.437" cutplane="0.0">
            <position x="0" y="3" z="-55"/>
            <material_solid>
                <color r="0.0" g="0.6" b="1"/>
                <phong ka="0.9" kd="1" ks="9" exponent="80"/>
                <reflectance r="0"/>
                <transmittance t="1"/>
                <refraction iof="1.0" ec="1"/>
            </material_solid>
        </julia>
        <mesh name="plane_small.obj">
            <material_solid>
                <color r="0.3" g="0.2" b="0.3"/>
                <phong ka="0.0" kd="0" ks="0" exponent="80"/>
                <reflectance r="1"/>
                <transmittance t="0"/>
                <refraction iof="1.5" ec="1"/>
            </material_solid>
            <transform>
                <translate x="0.0" y="-8" z="-292.5"/>
                <scale x="100" y="1" z="297.5"/>
                <rotateX theta="-90.0"/>
            </transform>
        </mesh>
    </surfaces>
</scene>

=== clemy/RayTracer/examples3/102_fresnel_animation.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE scene SYSTEM "scene.dtd">

<scene output_file="102_fresnel_animation.png">
    <background_color r="0.0" g="0.0" b="0.0"/>
  <animation length="2" fps="13"/>
    <camera>
        <position x="0;3(b)" y="0;2(b)" z="-2;-4(b)"/>
        <lookat x="0.0" y="0.0" z="-6.5"/>
        <up x="0.0" y="1.0" z="0.0"/>
        <horizontal_fov angle="45"/>
        <resolution horizontal="300" vertical="300"/>
        <max_bounces n="8"/>
    </camera>
    <lights>
        <ambient_light>
            <color r="1.0" g="1.0" b="1.0"/>
        </ambient_light>
        <point_light>
            <color r="0.7" g="0.7" b="0.7"/>
            <position x="2.0" y="3.0" z="-2.5"/>
        </point_light>
        <point_light>
            <color r="0.7" g="0.7" b="0.7"/>
            <position x="-2.0" y="3.0" z="-2.5"/>
        </point_light>
    </lights>
    <surfaces>
        <mesh name="open_room.obj">
            <material_solid>
                <color r="0.6" g="0.6" b="0.6"/>
                <phong ka="0.3" kd="0.9" ks="1.0" exponent="20"/>
                <reflectance r="0.0"/>
                <transmittance t="0.0"/>
                <refraction iof="0.0"/>
            </material_solid>
        </mesh>
        <mesh name="wall.obj">
            <material_textured>
                <texture name="mramor6x6.png"/>
                <phong ka="0.3" kd="0.9" ks="1.0" exponent="200"/>
                <reflectance r="0.0"/>
                <transmittance t="0.0"/>
                <refraction iof="0.0"/>
            </material_textured>
        </mesh>
      <mesh name="box2.obj">
        <material_solid>
          <color r="0.17" g="0.18" b="0.50"/>
          <phong ka="0.0" kd="0.0" ks="0.0" exponent="200"/>
          <reflectance r="0.8"/>
          <transmittance t="0.8"/>
          <refraction iof="1.5168" ec="9.7525e-9" disp="-0.2"/>
        </material_solid>
      </mesh>
    </surfaces>
</scene>

=== clemy/RayTracer/examples2/5_julia_animation.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE scene SYSTEM "scene.dtd">

<scene output_file="5_julia_animation.png">
    <background_color r="0.0" g="0.0" b="0.0" a="1"/>
    <animation length="3.0" fps="15"/>
    <camera>
        <position x="0.0" y="0.0" z="1.0"/>
        <lookat x="0.0" y="0.0" z="-2.5"/>
        <up x="0.0" y="1.0" z="0.0"/>
        <horizontal_fov angle="45"/>
        <resolution horizontal="512" vertical="512"/>
        <max_bounces n="8"/>
    </camera>
    <lights>
        <ambient_light>
            <color r="1.0" g="1.0" b="1.0"/>
        </ambient_light>
        <point_light>
            <color r="0.7" g="0.7" b="0.7"/>
            <position x="2.0" y="3.0" z="-1.5"/>
        </point_light>
        <point_light>
            <color r="0.7" g="0.7" b="0.7"/>
            <position x="-2.0" y="3.0" z="-1.5"/>
        </point_light>
    </lights>
    <surfaces>
        <julia scale="2" cr="-0.291" ca="-0.399" cb="0.339" cc="0.437" cutplane="-1;1">
            <position x="0.0" y="0.0" z="-4.0"/>
            <material_solid>
                <color r="0.37" g="0.38" b="0.70"/>
                <phong ka="0.3" kd="0.9" ks="0.6" exponent="200"/>
                <reflectance r="0.0"/>
                <transmittance t="0.0"/>
                <refraction iof="0.0"/>
            </material_solid>
        </julia>
    </surfaces>
</scene>

=== clemy/RayTracer/wasm/examples/104_julia_animation.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE scene SYSTEM "scene.dtd">

<scene output_file="104_julia_animation.png">
    <background_color r="0.0" g="0.0" b="0.1" a="1"/>
    <animation length="5" fps="15"/>
    <camera>
        <position x="0;20(b,0.5);0.0" y="0.0;20(b,0.5);0.0" z="0.0;-20(b,0.5);0.0"/>
        <lookat x="0.0" y="0.0;3(b,0.5);0.0" z="-55"/>
        <up x="0.0" y="1.0" z="0.0"/>
        <horizontal_fov angle="22.5"/>
        <resolution horizontal="320" vertical="200"/>
        <supersampling subpixels_peraxis="1"/>
        <max_bounces n="8"/>
    </camera>
    <lights>
        <ambient_light>
            <color r="0.1" g="0.1" b="0.1"/>
        </ambient_light>
        <point_light>
            <color r="0.25" g="0.55" b="0.05"/>
            <position x="-30" y="25" z="0"/>
        </point_light>
        <point_light>
            <color r="0.45" g="0.45" b="0.45"/>
            <position x="2.0" y="5.0" z="0"/>
        </point_light>
        <point_light>
            <color r="0.0" g="0.0" b="0.45"/>
            <position x="20" y="0" z="-20"/>
        </point_light>
    </lights>
    <surfaces>
        <julia scale="13" cr="-0.291" ca="-0.399" cb="0.339" cc="0.437" cutplane="-1;1">
            <position x="0" y="3" z="-55"/>
            <material_solid>
                <color r="0.0" g="0.6" b="1"/>
                <phong ka="0.9" kd="1" ks="9" exponent="80"/>
                <reflectance r="0"/>
                <transmittance t="0"/>
                <refraction iof="1.0" ec="1"/>
            </material_solid>
        </julia>
    </surfaces>
</scene>

=== clemy/RayTracer/wasm/examples/3_motionblur.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE scene SYSTEM "scene.dtd">

<scene output_file="3_motionblur.png">
    <background_color r="0.0" g="0.0" b="0.0"/>
    <animation length="2" fps="8"/>
    <still time="0.6"/>
    <motionblur subframes="10"/>
    <camera>
        <position x="3.0" y="2.0" z="-3.0"/>
        <lookat x="0.0" y="0.0" z="-6.5"/>
        <up x="0.0" y="1.0" z="0.0"/>
        <horizontal_fov angle="45"/>
        <resolution horizontal="512" vertical="512"/>
        <max_bounces n="8"/>
    </camera>
    <lights>
        <ambient_light>
            <color r="1.0" g="1.0" b="1.0"/>
        </ambient_light>
        <point_light>
            <color r="0.3" g="0.3" b="0.3"/>
            <position x="2.0" y="1.0" z="-2.5"/>
        </point_light>
        <point_light>
            <color r="0.3" g="0.3" b="0.3"/>
            <position x="-2.0" y="-1.0" z="-2.5"/>
        </point_light>
        <point_light>
            <color r="0.7" g="0.7" b="0.7"/>
            <position x="4.0" y="10.0" z="-1"/>
        </point_light>
    </lights>
    <surfaces>
        <mesh name="open_room.obj">
            <material_textured>
                <texture name="rainbow.png"/>
                <phong ka="0.3" kd="0.9" ks="1.0" exponent="200"/>
                <reflectance r="0.0"/>
                <transmittance t="0.0"/>
                <refraction iof="0.0"/>
            </material_textured>
            <transform>
                <translate x="0" y="0" z="0"/>
            </transform>
        </mesh>
        <mesh name="plane_small.obj">
            <material_textured>
                <texture name="mramor6x6.png"/>
                <phong ka="0.3" kd="0.9" ks="1.0" exponent="200"/>
                <reflectance r="0.0"/>
                <transmittance t="0.0"/>
                <refraction iof="0.0"/>
            </material_textured>
            <transform>
                <translate x="-0.33" y="-2.45" z="-0.67"/>
                <scale x="20" y="1" z="20"/>
                <rotateX theta="-90"/>
            </transform>
        </mesh>
        <mesh name="cone.obj">
            <material_solid>
                <color r="0.50" g="0.18" b="0.17"/>
                <phong ka="0.3" kd="0.9" ks="1.0" exponent="200"/>
                <reflectance r="0.0"/>
                <transmittance t="0.0"/>
                <refraction iof="0"/>
            </material_solid>
            <transform>
                <translate x="0" y="-1.5;5(i)" z="-1"/>
            </transform>
        </mesh>
        <mesh name="cone.obj">
            <material_solid>
                <color r="0.17" g="0.50" b="0.18"/>
                <phong ka="0.3" kd="0.9" ks="1.0" exponent="200"/>
                <reflectance r="0.0"/>
                <transmittance t="0.0"/>
                <refraction iof="0"/>
            </material_solid>
            <transform>
                <translate x="-3" y="-1.5" z="0"/>
            </transform>
        </mesh>
        <mesh name="cone.obj">
            <material_solid>
                <color r="0.17" g="0.17" b="0.50"/>
                <phong ka="0.3" kd="0.9" ks="1.0" exponent="200"/>
                <reflectance r="0.0"/>
                <transmittance t="0.0"/>
                <refraction iof="0"/>
            </material_solid>
            <transform>
                <translate x="3" y="-1.5" z="-2"/>
            </transform>
        </mesh>
    </surfaces>
</scene>
